'use strict';
(function(D){
const $=s=>document.querySelector(s),g=new D.Game(),renderer=new D.Renderer($('#game'),$('#mini'),g),panel=$('#panel'),overlay=$('#overlay'),roman=n=>n>20?String(n):['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX'][n],escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.__DTD__={game:g,renderer,version:'4.0.0-cloister',catalogue:D.RELICS};let last=0,hudClock=0,toastTimer=0,joyId=null,dashId=null,lab=false;const keys=new Set();
function clearInput(){joyId=null;dashId=null;g.input.x=g.input.y=0;g.player.vx=g.player.vy=0;keys.clear();$('#stick').style.transform='';}
function show(html){clearInput();overlay.classList.remove('hidden');document.body.classList.add('paused');panel.innerHTML=html;overlay.scrollTop=0;}
function hide(){overlay.classList.add('hidden');document.body.classList.remove('paused');clearInput();}
function actions(items){return `<div class="actions">${items.map(([id,text,primary])=>`<button class="${primary?'primary':'secondary'}" id="${id}">${text}</button>`).join('')}</div>`;}
function button(id,fn){const e=$('#'+id);if(e)e.onclick=fn;}
function title(){g.paused=true;g.state='title';show(`<div class="introLayout"><div><div class="eyebrow">ENDLESS COVENANT · THE SUNKEN CLOISTER</div><div class="introCrest">♆</div><h1 class="title">Draft<br><em>the Devil.</em></h1><p class="lead">Take his power.<br>Live with your choices.</p></div><div class="rules"><p><b>One for you. One for him.</b><br>Choose from three relics. Give another to the Devil. After ten waves, defeat the creature you helped create.</p><p><b>Break the covenant. Keep the build.</b><br>Claim a tier of his power and descend again. Fifty-six relics. Five tiers. One more run.</p>${actions([['begin','ENTER THE COVENANT',true],['workshop','RELIC WORKSHOP']])}<p class="fine">Move with your left thumb. Dash with your right.<br>Auto-aim and auto-fire · iPhone + iPad · landscape recommended</p><p class="fine">BUILD 4.0 · CLOISTER · 56 RELICS<br>The workshop lets you test any tier without waiting for a draft.</p></div></div>`);button('begin',()=>{lab=false;g.start();});button('workshop',workshop);}
function card(id,mode='take'){const r=D.R[id],lv=g.levels[id]||0,next=Math.min(5,lv+1),devil=g.devil[id]||0;return `<button class="card ${next===5?'ascend':''}" data-relic="${id}"><div class="icon">${r.icon}</div><div class="tier">${mode==='devil'?'THE DEVIL · TIER '+roman(Math.min(5,devil+1)):mode==='trophy'?'CLAIM TIER '+roman(next):next===5?'ASCENSION · TIER V':lv?'UPGRADE · TIER '+roman(next):'NEW · TIER I'}</div><h3>${escape(r.name)}</h3><div class="desc">${escape(mode==='devil'?D.devilEffect(id,Math.min(5,devil+1)):r.tiers[next-1])}</div><div class="take">${mode==='devil'?(devil>=5?'ALREADY MAXED · NO EXTRA TIER':'GIVE TO THE DEVIL'):mode==='trophy'?'STEAL ONE TIER':'TAKE THIS RELIC'}</div></button>`;}
function selectCards(fn){panel.querySelectorAll('[data-relic]').forEach(e=>e.onclick=()=>fn(e.dataset.relic));}
function draft(choices){if(!choices.length){show(`<div class="eyebrow">EVERY RELIC HAS ASCENDED</div><h2 class="draftTitle">Your collection is complete.</h2><p class="lead">The covenant continues. Restore 20 health and face the next wave.</p>${actions([['advance','CONTINUE',true]])}`);button('advance',()=>{g.heal(20);g.afterDraft();});return;}show(`<div class="eyebrow">WAVE ${g.wave} CLEARED · COVENANT ${roman(g.cycle)}</div><h2 class="draftTitle">What will you become?</h2><p class="draftSub">Choose your relic. Then choose which remaining relic empowers the Devil.</p><div class="cards ${choices.length===2?'two':''}">${choices.map(id=>card(id)).join('')}</div><div class="fine">Upgrades have 1.2× the per-relic draw weight of new relics. The unchosen third returns to the pool.</div>`);selectCards(id=>g.take(id));}
function devilDraft(choices){show(`<div class="eyebrow">THE PRICE OF POWER</div><h2 class="draftTitle">Choose his inheritance.</h2><p class="draftSub">One becomes the Devil’s. The other returns to the pool.</p><div class="cards ${choices.length===2?'two':''}">${choices.map(id=>card(id,'devil')).join('')}</div>`);selectCards(id=>g.give(id));}
function preboss(){const names=Object.entries(g.devil).filter(([,v])=>v>0).map(([id,n])=>`${D.R[id].icon} ${escape(D.R[id].name)} ${roman(n)}`).join(' · ');show(`<div class="eyebrow">COVENANT ${roman(g.cycle)} · FINAL ENCOUNTER</div><h2 class="draftTitle">The Devil remembers.</h2><p class="lead">A short, dangerous fight. His attacks leave openings.<br>The power you gave him is now the power you can steal.</p><div class="sectionFrame fine">${names}</div>${actions([['fight','FACE THE DEVIL',true]])}`);button('fight',()=>g.spawnBoss());}
function trophy(choices){show(`<div class="eyebrow">COVENANT ${roman(g.cycle)} BROKEN</div><h2 class="draftTitle">Claim what you gave away.</h2><p class="draftSub">You gain one tier. The Devil permanently loses that tier.</p>${choices.length?`<div class="cards ${choices.length===2?'two':''}">${choices.map(id=>card(id,'trophy')).join('')}</div>`:`<p class="lead">You have mastered everything he carries.</p>${actions([['descend','DESCEND TO THE NEXT COVENANT',true]])}`}`);if(choices.length)selectCards(id=>g.claim(id));else button('descend',()=>g.next());}
function summary(id){show(`<div class="eyebrow">THE TROPHY IS YOURS</div><h2 class="draftTitle">${escape(D.R[id].name)} · ${roman(g.levels[id])}</h2><p class="lead">${escape(D.R[id].tiers[g.levels[id]-1])}</p><div class="sectionFrame stats"><div><b>${g.kills}</b><span>KILLS</span></div><div><b>${Object.values(g.levels).reduce((a,b)=>a+b,0)}</b><span>RELIC TIERS</span></div><div><b>${D.SYNERGIES.filter(([a,b])=>g.syn(a,b)).length}</b><span>SYNERGIES</span></div></div>${actions([['descend','DESCEND TO COVENANT '+roman(g.cycle+1),true],['quit','SEAL THIS RUN']])}`);button('descend',()=>g.next());button('quit',endScreen);}
function endScreen(){g.paused=true;g.state='end';lab=false;show(`<div class="eyebrow">THE CONTRACT CLOSES</div><h2 class="draftTitle">The Devil collects.</h2><p class="lead">Your next draft can tell a different story.</p><div class="sectionFrame stats"><div><b>${roman(g.cycle)}</b><span>COVENANT</span></div><div><b>${g.wave}</b><span>WAVE</span></div><div><b>${g.kills}</b><span>KILLS</span></div></div>${actions([['again','BEGIN AGAIN',true],['menu','MAIN MENU']])}`);button('again',()=>g.start());button('menu',title);}
function pause(){if(!['wave','boss','lab'].includes(g.state))return;g.paused=true;show(`<div class="eyebrow">YOUR COVENANT IS SAFE</div><h2 class="draftTitle">Take a breath.</h2>${actions([['resume','RESUME',true],['journal','RELIC JOURNAL'],['settings','CONTROLS & DISPLAY'],['workshop','RELIC WORKSHOP']])}<p class="fine">Opening the workshop starts a separate test session. Your current run will be replaced.</p>`);button('resume',()=>{g.paused=false;hide();});button('journal',journal);button('settings',settings);button('workshop',workshop);}
function journal(){g.paused=true;const entries=Object.entries(g.levels).filter(([,n])=>n>0);show(`<div class="eyebrow">YOUR RELIQUARY</div><h2 class="draftTitle">The power you carry.</h2><div class="catalogue">${entries.length?entries.map(([id,n])=>{const r=D.R[id];return `<div class="entry"><strong>${r.icon} ${escape(r.name)} · ${roman(n)}</strong>${r.tiers.map((d,i)=>`<p class="${i<n?'':'inactive'}">${roman(i+1)} · ${escape(d)}</p>`).join('')}</div>`;}).join(''):'<div class="entry">Survive a wave to draft your first relic.</div>'}</div><div class="synergy">${D.SYNERGIES.filter(([a,b])=>g.syn(a,b)).map(s=>`<b>${escape(s[2])}</b> — ${escape(s[3])}`).join('<br>')||'Your next relic may unlock a new interaction.'}</div>${actions([['resume','RESUME',true],['back','PAUSE MENU']])}`);button('resume',()=>{g.paused=false;hide();});button('back',pause);}
function settings(){g.paused=true;show(`<div class="eyebrow">IPHONE · IPAD · DESKTOP</div><h2 class="draftTitle">Make it feel right.</h2><div class="settings"><label>Thumb layout <select id="hand"><option value="normal">Move left · dash right</option><option value="swap">Move right · dash left</option></select></label><label>Control size <select id="size"><option value="auto">Automatic</option><option value="90">Compact</option><option value="116">Comfort</option><option value="142">Large / iPad</option></select></label><label>Rendering <select id="quality"><option value="1.5">Balanced</option><option value="2">High detail</option><option value="1">Battery saver</option></select></label></div><p class="fine">The controls are anchored inside the game’s viewport and respect device safe areas.<br>WASD / arrows move · Space dashes · Escape pauses.</p>${actions([['resume','RETURN TO GAME',true]])}`);$('#hand').value=$('#app').classList.contains('leftHanded')?'swap':'normal';$('#hand').onchange=e=>$('#app').classList.toggle('leftHanded',e.target.value==='swap');$('#size').onchange=e=>{if(e.target.value==='auto')$('#app').style.removeProperty('--control');else $('#app').style.setProperty('--control',e.target.value+'px');clearInput();};$('#quality').value=String(renderer.quality);$('#quality').onchange=e=>{renderer.quality=Number(e.target.value);renderer.resize();};button('resume',()=>{g.paused=false;hide();});}
function workshop(){g.paused=true;show(`<div class="eyebrow">RELIC WORKSHOP · SEPARATE TEST SESSION</div><h2 class="draftTitle">See the effect yourself.</h2><p class="draftSub">Choose any relic and tier. The workshop is invulnerable and keeps spawning test enemies.</p><div class="settings workshop"><label>Relic <select id="labRelic">${D.RELICS.map(r=>`<option value="${r.id}">${escape(r.name)}</option>`).join('')}</select></label><label>Tier <select id="labTier">${[1,2,3,4,5].map(n=>`<option value="${n}">${roman(n)}${n===5?' · ASCENSION':''}</option>`).join('')}</select></label><label>Pair with <select id="labPair"><option value="">No second relic</option>${D.RELICS.map(r=>`<option value="${r.id}">${escape(r.name)}</option>`).join('')}</select></label></div><p id="labDesc" class="lead"></p>${actions([['launchLab','ENTER THE WORKSHOP',true],['back','MAIN MENU']])}`);const desc=()=>$('#labDesc').textContent=D.R[$('#labRelic').value].tiers[Number($('#labTier').value)-1];$('#labRelic').onchange=desc;$('#labTier').onchange=desc;desc();button('launchLab',()=>{const id=$('#labRelic').value,n=Number($('#labTier').value),pair=$('#labPair').value;g.start();g.state='lab';g.levels[id]=n;if(pair&&pair!==id)g.levels[pair]=3;g.stats=g.calcStats();g.player.hp=g.stats.maxHp;g.wave=6;lab=true;hide();for(let i=0;i<20;i++)g.enemy(i%4===0?'brute':'penitent',g.player.x+Math.cos(i)*100,g.player.y+Math.sin(i)*100,i%4===0);});button('back',title);}
function updateHud(){const p=g.player,s=g.stats;$('#hpbar').style.width=Math.max(0,p.hp/s.maxHp*100)+'%';$('#hptext').textContent=Math.max(0,Math.ceil(p.hp))+' / '+s.maxHp;$('#shieldtext').textContent=p.shield>0?'+'+Math.ceil(p.shield)+' WARD':'';$('#kills').textContent=g.kills;$('#time').textContent=String(Math.floor(g.time/60)).padStart(2,'0')+':'+String(Math.floor(g.time%60)).padStart(2,'0');$('#covenant').textContent=lab?'RELIC WORKSHOP':'COVENANT '+roman(g.cycle);$('#wave').textContent=g.state==='boss'?'THE DEVIL':lab?'INVULNERABLE · TRY A COMBINATION':'WAVE '+g.wave+' / 10';$('#wavebar').style.width=Math.min(100,g.waveTime/22*100)+'%';$('#dashText').textContent=p.dash>0?p.dash.toFixed(1)+'s':'DASH';$('#dash').classList.toggle('cool',p.dash>0);$('#bossHud').classList.toggle('on',g.state==='boss'&&g.boss&&!g.boss.dead);if(g.boss){$('#bossFill').style.width=Math.max(0,g.boss.hp/g.boss.maxHp*100)+'%';$('#bossNumbers').textContent=Math.ceil(Math.max(0,g.boss.hp))+' / '+Math.ceil(g.boss.maxHp)+(g.boss.ward>0?' · WARDED':'');}$('#relicrail').innerHTML=Object.entries(g.levels).filter(([,v])=>v>0).slice(-18).map(([id,n])=>`<span class="relicpip ${n===5?'max':''}">${D.R[id].icon}<b>${roman(n)}</b></span>`).join('');}
function toast(data){$('#notice strong').textContent=data.title||'';$('#notice small').textContent=data.text||'';$('#notice').classList.add('on');toastTimer=1.8;}
g.listeners.push((ev,data)=>{if(ev==='start'||ev==='resume')hide();if(ev==='draft')draft(data.choices);if(ev==='devilDraft')devilDraft(data.choices);if(ev==='preboss')preboss();if(ev==='trophy')trophy(data.choices);if(ev==='claimed')summary(data.id);if(ev==='end')endScreen();if(ev==='toast')toast(data);});
function joyMove(e){const r=$('#joy').getBoundingClientRect(),max=r.width*.37,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,m=Math.hypot(dx,dy),k=m>max?max/m:1;g.input.x=dx*k/max;g.input.y=dy*k/max;$('#stick').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
$('#joy').addEventListener('pointerdown',e=>{if(g.paused||joyId!==null)return;e.preventDefault();joyId=e.pointerId;$('#joy').setPointerCapture(e.pointerId);joyMove(e);});$('#joy').addEventListener('pointermove',e=>{if(e.pointerId===joyId){e.preventDefault();joyMove(e);}});function stopJoy(e){if(e.pointerId===joyId){joyId=null;g.input.x=g.input.y=0;g.player.vx=g.player.vy=0;$('#stick').style.transform='';}}for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('#joy').addEventListener(ev,stopJoy);
$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();if(g.paused)return;dashId=e.pointerId;g.dash();});
addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement||e.target instanceof HTMLInputElement)return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape'){if(g.paused&&['wave','boss','lab'].includes(g.state)){g.paused=false;hide();}else pause();return;}if(k===' '){g.dash();return;}keys.add(k);g.input.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);g.input.y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());g.input.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);g.input.y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);});
function doResize(){clearInput();renderer.resize();}addEventListener('resize',doResize);if(window.visualViewport)visualViewport.addEventListener('resize',doResize);addEventListener('blur',()=>{clearInput();if(!g.paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(!g.paused)pause();}last=0;});
button('pause',pause);button('journalBtn',journal);$('#rotateHint').onclick=()=>$('#rotateHint').style.display='none';
function loop(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;if(lab&&!g.paused){g.player.ifr=5;if(g.enemies.length<25&&g.ready('labSpawn',.35,dt))g.spawn();}g.update(dt);renderer.draw(dt);hudClock-=dt;if(hudClock<=0){updateHud();hudClock=.12;}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#notice').classList.remove('on');}requestAnimationFrame(loop);}title();requestAnimationFrame(loop);
})(window.DTD);
