'use strict';
const enemyDefs={
penitent:{r:13,hp:22,sp:75,dmg:8,col:'#77443f'},
cantor:{r:12,hp:19,sp:57,dmg:7,col:'#6d5360'},
brute:{r:21,hp:75,sp:39,dmg:16,col:'#5a3934'},
hound:{r:11,hp:27,sp:135,dmg:9,col:'#7b4b32'},
wisp:{r:10,hp:22,sp:105,dmg:8,col:'#536b72'},
bell:{r:19,hp:95,sp:48,dmg:14,col:'#5b5042'},
herald:{r:15,hp:48,sp:61,dmg:10,col:'#67454e'},
moth:{r:10,hp:28,sp:92,dmg:7,col:'#6b5c72'}
};
function enemyType(){let x=Math.random(),w=wave+(cycle-1)*3;if(w<2)return'penitent';if(w<4)return x<.23?'cantor':x>.84?'hound':'penitent';if(w<7)return x<.16?'cantor':x<.3?'hound':x>.82?'brute':'penitent';return x<.12?'cantor':x<.24?'hound':x<.37?'wisp':x<.49?'bell':x<.62?'herald':x<.72?'moth':x<.84?'brute':'penitent'}
function spawnEnemy(){let a=Math.random()*TAU,rad=Math.max(W,H)*.6+rnd(280,120),t=enemyType(),d=enemyDefs[t],sc=1+(cycle-1)*.38+(wave-1)*.1,elite=Math.random()<Math.min(.22,.012*(wave+cycle*2));enemies.push({x:P.x+Math.cos(a)*rad,y:P.y+Math.sin(a)*rad,vx:0,vy:0,t,r:d.r*(elite?1.16:1),hp:d.hp*sc*(elite?2.1:1),maxHp:d.hp*sc*(elite?2.1:1),speed:d.sp*(1+.02*cycle),damage:d.dmg*(1+.08*cycle),elite,fire:rnd(2,.3),special:rnd(4,1),burn:0,bleed:0,bleedStacks:0,slow:0,void:0,dead:false})}
function nearestEnemy(x=P.x,y=P.y){let best=null,bd=1e9;for(const e of enemies){if(e.dead)continue;let d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;best=e}}if(state==='boss'&&boss&&!boss.dead){let d=(boss.x-x)**2+(boss.y-y)**2;if(d<bd)best=boss}return best}
let shotN=0;
function firePlayer(){let t=nearestEnemy();if(!t)return;let a=Math.atan2(t.y-P.y,t.x-P.x),volley=(++shotN),n=P.shots,fan=0;if(has('trinity')&&volley%(has('trinity',2)?8:10)===0){n=has('trinity',5)?7:3;fan=.17}for(let i=0;i<n;i++){let aa=a+(i-(n-1)/2)*fan;makeShot(P.x,P.y,aa,P.damage,1,P.pierce,volley)}if(has('mirror')&&volley%(has('mirror',2)?4:6)===0){let dirs=has('mirror',5)?4:1;for(let k=0;k<dirs;k++)makeShot(P.x,P.y,a+Math.PI+k*TAU/dirs,P.damage*(has('mirror',3)?1:.75),1,P.pierce,volley)}if(has('split')&&volley%(has('split',2)?6:8)===0){for(let q=-1;q<=1;q++)makeShot(P.x,P.y,a+q*.28,P.damage*(has('split',3)?.85:.65),.85,P.pierce,volley,true)}}
function makeShot(x,y,a,dmg,scale=1,pierce=0,count=0,split=false){shots.push({x,y,vx:Math.cos(a)*P.shotSpeed,vy:Math.sin(a)*P.shotSpeed,r:4.3*scale,life:1.8,damage:dmg,pierce:has('pierce',5)?6:pierce,owner:'p',count,split,bounces:P.ricochet?Math.min(4,P.ricochet):0})}
function enemyShot(src,a,sp=280,dmg=8,kind='bolt'){shots.push({x:src.x,y:src.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:kind==='orb'?7:4.7,life:4,damage:dmg,owner:'e',kind})}
function update(dt){
 if(paused)return;totalTime+=dt;P.ifr=Math.max(0,P.ifr-dt);P.dashLeft=Math.max(0,P.dashLeft-dt);if(P.regen)P.hp=Math.min(P.maxHp,P.hp+P.regen*dt);
 let mx=joy.x,my=joy.y,mag=Math.hypot(mx,my);if(mag>.08){let nx=mx/mag,ny=my/mag,target=P.speed*Math.min(1,mag);P.vx=nx*target;P.vy=ny*target}else{P.vx*=Math.pow(.015,dt);P.vy*=Math.pow(.015,dt);if(Math.abs(P.vx)<2)P.vx=0;if(Math.abs(P.vy)<2)P.vy=0}
 P.x+=P.vx*dt;P.y+=P.vy*dt;camera.x+=(P.x-camera.x)*Math.min(1,dt*10);camera.y+=(P.y-camera.y)*Math.min(1,dt*10);
 if(state==='wave'){waveTime+=dt;let dur=17+Math.min(8,(cycle-1)*1.2);spawnClock-=dt;if(spawnClock<=0&&enemies.length<34+cycle*4){spawnEnemy();if(wave>5&&Math.random()<.16)spawnEnemy();spawnClock=Math.max(.16,.62/(1+wave*.07+cycle*.08))}if(waveTime>=dur)finishWave()}
 shotClock-=dt;if(shotClock<=0){firePlayer();shotClock=P.fireRate}
 updateEnemies(dt);updateBoss(dt);updateShots(dt);updatePickups(dt);updateHazards(dt);updateParticles(dt);applyPassive(dt);if(P.hp<=0)endRun(false);updateUI()
}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;let a=Math.atan2(P.y-e.y,P.x-e.x),d=dist(P,e),slow=e.slow>0?(has('frost',2)?.55:.72):1;e.slow=Math.max(0,e.slow-dt);if(e.burn>0){e.burn-=dt;e.hp-=P.burnDps*dt}if(e.bleed>0){e.bleed-=dt;e.hp-=P.bleedDps*e.bleedStacks*dt}let sp=e.speed*slow;
 if(e.t==='cantor'||e.t==='wisp'||e.t==='herald'){let ideal=e.t==='wisp'?280:235;let dir=d<ideal?-1:1;e.x+=Math.cos(a)*sp*dir*dt;e.y+=Math.sin(a)*sp*dir*dt;e.fire-=dt;if(e.fire<=0){if(e.t==='cantor'){for(let i=-1;i<=1;i++)enemyShot(e,a+i*.13,250,e.damage)}else if(e.t==='wisp'){enemyShot(e,a,360,e.damage,'orb')}else{for(let i=0;i<5;i++)enemyShot(e,a+(i-2)*.18,230,e.damage)}e.fire=e.t==='herald'?2.6:1.7}}
 else if(e.t==='hound'){e.special-=dt;if(e.special<=0){e.vx=Math.cos(a)*430;e.vy=Math.sin(a)*430;e.special=2.8}e.vx*=.96;e.vy*=.96;e.x+=(Math.cos(a)*sp+e.vx)*dt;e.y+=(Math.sin(a)*sp+e.vy)*dt}
 else if(e.t==='bell'){e.x+=Math.cos(a)*sp*dt;e.y+=Math.sin(a)*sp*dt;e.special-=dt;if(e.special<=0){hazards.push({x:e.x,y:e.y,r:12,max:150,life:1.2,dmg:e.damage*1.1,type:'ring',enemy:true});e.special=4.2}}
 else if(e.t==='moth'){e.x+=Math.cos(a+Math.sin(totalTime*3)*.6)*sp*dt;e.y+=Math.sin(a+Math.sin(totalTime*3)*.6)*sp*dt;e.fire-=dt;if(e.fire<=0){for(let i=0;i<6;i++)enemyShot(e,i*TAU/6,190,e.damage*.8);e.fire=2.3}}
 else {e.x+=Math.cos(a)*sp*dt;e.y+=Math.sin(a)*sp*dt}
 if(d<P.r+e.r)hurtPlayer(e.damage,e);if(e.hp<=0)killEnemy(e)}
 enemies=enemies.filter(e=>!e.dead&&dist(e,P)<1800)
}
function updateBoss(dt){if(state!=='boss'||!boss||boss.dead)return;let a=Math.atan2(P.y-boss.y,P.x-boss.x),d=dist(P,boss),lv=id=>devilLv[id]||0;
 boss.fireClock-=dt;if(boss.fireClock<=0){let n=1+(lv('fork')>=1?Math.min(4,lv('fork')):0)+(lv('trinity')>=1&&Math.random()<.25?2:0);for(let i=0;i<n;i++)enemyShot(boss,a+(i-(n-1)/2)*.17,300+lv('rapid')*18,boss.damage*(1+lv('glass')*.13));if(lv('mirror')>=1)enemyShot(boss,a+Math.PI*.35,280,boss.damage*.8);boss.fireClock=Math.max(.28,1.05-lv('rapid')*.1)}
 boss.dashClock-=dt;if(boss.dashClock<=0){boss.vx=Math.cos(a)*(430+lv('swift')*35);boss.vy=Math.sin(a)*(430+lv('swift')*35);boss.dashClock=Math.max(1.5,3.5-lv('swift')*.22)}
 boss.vx=(boss.vx||0)*.965;boss.vy=(boss.vy||0)*.965;boss.x+=(Math.cos(a)*boss.speed+boss.vx)*dt;boss.y+=(Math.sin(a)*boss.speed+boss.vy)*dt;
 if(lv('ember')){boss.trail=(boss.trail||0)-dt;if(boss.trail<=0){hazards.push({x:boss.x,y:boss.y,r:35+lv('ember')*4,life:4,dmg:4+lv('ember')*2,type:'fire',enemy:true});boss.trail=.5}}
 if(lv('storm')){boss.storm=(boss.storm||2)-dt;if(boss.storm<=0){hazards.push({x:P.x+rnd(80,-80),y:P.y+rnd(80,-80),r:14,max:70,life:.8,dmg:12+lv('storm')*3,type:'lightning',enemy:true});boss.storm=Math.max(1.6,3.2-lv('storm')*.2)}}
 if(lv('seraph')){boss.lance=(boss.lance||3)-dt;if(boss.lance<=0){for(let i=0;i<Math.min(7,2+lv('seraph'));i++)hazards.push({x:P.x+rnd(180,-180),y:P.y+rnd(120,-120),r:10,max:45,life:1.0,dmg:10+lv('seraph')*2,type:'lance',enemy:true});boss.lance=4}}
 if(lv('heart')>=4)boss.hp=Math.min(boss.maxHp,boss.hp+(1.4*lv('heart'))*dt);
 if(lv('ward')){boss.ward=(boss.ward||4)-dt;if(boss.ward<=0){boss.shield=1.4+.25*lv('ward');boss.ward=5}boss.shield=Math.max(0,(boss.shield||0)-dt)}
 if(d<P.r+boss.r)hurtPlayer(boss.contact,boss);ui.bossFill.style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';
 if(boss.hp<=0&&!boss.dead){if(lv('phoenix')>=1&&!boss.revived){boss.revived=true;boss.hp=boss.maxHp*(lv('phoenix')>=5?.55:.28);toast('THE DEVIL RISES','PHOENIX CLAUSE')}else beatBoss()}
}
function updateShots(dt){for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.owner==='p'&&s.bounces>0){let px=s.x-camera.x+W/2,py=s.y-camera.y+H/2;if(px<20||px>W-20){s.vx*=-1;s.bounces--}if(py<20||py>H-20){s.vy*=-1;s.bounces--}}}handleCollisions();shots=shots.filter(s=>s.life>0&&dist(s,P)<1700)}
function hitEnemy(e,s){let crit=Math.random()<P.crit,dmg=s.damage;if(P.execute&&e.hp/e.maxHp<(P.execute>=2?.27:.2))dmg*=1.35;if(e.void)dmg*=1.12;if(crit)dmg*=P.critMult;e.hp-=dmg;if(P.burn){e.burn=Math.max(e.burn,2.4)}if(P.freeze)e.slow=Math.max(e.slow,P.freeze);if(P.bleed){e.bleed=3;e.bleedStacks=Math.min(P.bleed>=2?5:3,(e.bleedStacks||0)+1)}if(P.voidMark)e.void=3;if(P.lifesteal)heal(dmg*P.lifesteal*(crit&&has('blood',4)?2:1));if(P.blast&&s.count%7===0)explode(e.x,e.y,P.blastDamage,has('blast',2)?105:72);if(crit&&has('crit',4)){let t=nearestEnemy(e.x,e.y);if(t&&t!==e){let a=Math.atan2(t.y-e.y,t.x-e.x);makeShot(e.x,e.y,a,P.damage*.65,.7,0,0)}}if(P.chain){chainFrom(e,P.chainDamage,has('fork',2)?2:1)}if(s.split&&has('split',4)&&crit){for(let q=-1;q<=1;q++)makeShot(e.x,e.y,Math.random()*TAU,P.damage*.45,.6,0,0)}hitFX(e.x,e.y,crit);if(e.hp<=0)killEnemy(e)}
function handleCollisions(){for(const s of shots){if(s.owner==='p'){if(state==='boss'&&boss&&!boss.dead&&dist(s,boss)<s.r+boss.r){if(!(boss.shield>0)){let fake={...boss,maxHp:boss.maxHp,void:0,bleedStacks:0,burn:0,slow:0};hitBoss(s,fake)}s.pierce--;if(s.pierce<0)s.life=0}for(const e of enemies){if(e.dead||s.life<=0)continue;if(dist(s,e)<s.r+e.r){hitEnemy(e,s);s.pierce--;if(s.pierce<0)s.life=0}}}else if(dist(s,P)<s.r+P.r){hurtPlayer(s.damage);s.life=0}}
 for(const h of hazards){if(h.enemy){let d=dist(h,P);if(h.type==='fire'&&d<h.r)hurtPlayer(h.dmg*.12);else if((h.type==='ring'||h.type==='lightning'||h.type==='lance')&&Math.abs(d-h.r)<12)hurtPlayer(h.dmg)}}
 if(P.orbit){let blades=P.orbit;for(let j=0;j<blades;j++){let a=totalTime*2.8+j*TAU/blades,o={x:P.x+Math.cos(a)*62,y:P.y+Math.sin(a)*62};for(const e of enemies)if(!e.dead&&dist(o,e)<e.r+9){e.hp-=P.orbitDamage/55;if(has('halo',4)&&P.bleed){e.bleed=2;e.bleedStacks=Math.min(5,(e.bleedStacks||0)+.03)}if(e.hp<=0)killEnemy(e)}if(boss&&dist(o,boss)<boss.r+9)boss.hp-=P.orbitDamage/55}}
}
function hitBoss(s,f){let crit=Math.random()<P.crit,dmg=s.damage;if(boss.hp/boss.maxHp<(P.execute>=2?.27:.2)&&P.execute)dmg*=1.35;if(crit)dmg*=P.critMult;boss.hp-=dmg;if(P.lifesteal)heal(dmg*P.lifesteal);if(P.blast&&s.count%7===0)boss.hp-=P.blastDamage;if(P.chain)boss.hp-=P.chainDamage*.45;hitFX(boss.x,boss.y,crit)}
function chainFrom(e,dmg,jumps){let cur=e,used=new Set([e]);for(let i=0;i<jumps;i++){let t=null,bd=has('fork',3)?240:170;for(const q of enemies){let d=dist(cur,q);if(!q.dead&&!used.has(q)&&d<bd){bd=d;t=q}}if(!t)break;t.hp-=dmg;if(synergyActive('fork','ember'))t.burn=2.2;used.add(t);cur=t;for(let k=0;k<4;k++)particle((cur.x+e.x)/2,(cur.y+e.y)/2,'#9bd3d0',70);if(t.hp<=0)killEnemy(t)}}
function explode(x,y,dmg,rad){for(const e of enemies)if(!e.dead&&Math.hypot(e.x-x,e.y-y)<rad){e.hp-=dmg;if(has('blast',3)&&P.burn)e.burn=2.5;if(has('frost',4)&&e.slow>0)e.hp-=dmg*.8;if(e.hp<=0)killEnemy(e)}if(boss&&Math.hypot(boss.x-x,boss.y-y)<rad)boss.hp-=dmg;hazards.push({x,y,r:8,max:rad,life:.35,dmg:0,type:'fx',enemy:false})}
function killEnemy(e){if(e.dead)return;e.dead=true;kills++;if(Math.random()<.63)pickups.push({x:e.x,y:e.y,dead:false,spin:Math.random()*TAU});if(has('ember',3)&&e.burn>0){for(const q of enemies)if(!q.dead&&dist(e,q)<105)q.burn=2}if(has('split',5)){for(let i=0;i<5;i++){let t=nearestEnemy(e.x,e.y);if(t)makeShot(e.x,e.y,Math.atan2(t.y-e.y,t.x-e.x)+rnd(.4,-.4),P.damage*.45,.65,0,0)}}if(has('seraph')){seraphCount=(seraphCount||0)+1;let req=has('seraph',2)?14:18;if(seraphCount>=req){seraphCount=0;hazards.push({x:e.x,y:e.y,r:8,max:70,life:.6,dmg:P.damage*2.4,type:'playerLance',enemy:false})}}if(synergyActive('ember','bleed')&&e.burn>0&&e.bleedStacks>=3)explode(e.x,e.y,P.burnDps*2.5,80);for(let i=0;i<8;i++)particle(e.x,e.y,e.elite?'#d0ae66':'#8f4b46',rnd(125,25))}
let seraphCount=0;
function updatePickups(dt){for(const g of pickups){let d=dist(g,P);g.spin+=dt*4;if(d<P.magnet){let a=Math.atan2(P.y-g.y,P.x-g.x),sp=220+(P.magnet-d)*2;g.x+=Math.cos(a)*sp*dt;g.y+=Math.sin(a)*sp*dt}if(d<P.r+9){g.dead=true;if(P.pickupHeal)heal(P.pickupHeal);if(synergyActive('magnet','soul'))soulVolley()}}pickups=pickups.filter(g=>!g.dead&&dist(g,P)<1400)}
function soulVolley(){if(!has('soul'))return;for(let i=0;i<Math.min(6,2+tier('soul'));i++){let t=nearestEnemy();if(t)makeShot(P.x,P.y,Math.atan2(t.y-P.y,t.x-P.x)+rnd(.25,-.25),P.damage*.38,.55,0,0)}}
function updateHazards(dt){for(const h of hazards){h.life-=dt;if(h.max)h.r+=(h.max-h.r)*Math.min(1,dt*7);if(!h.enemy&&h.type==='playerLance'&&h.life<.3){for(const e of enemies)if(!e.dead&&dist(h,e)<h.r){e.hp-=h.dmg;if(e.hp<=0)killEnemy(e)}}}hazards=hazards.filter(h=>h.life>0)}
function applyPassive(dt){if(P.curse){let rad=95+P.curse*13;for(const e of enemies)if(!e.dead&&dist(P,e)<rad){e.hp-=(2.5+P.curse*1.5)*(has('curse',4)?1+(1-P.hp/P.maxHp):1)*dt;if(P.voidMark&&has('curse',3))e.void=2;if(e.hp<=0)killEnemy(e)}}if(P.storm){stormCharge=(stormCharge||0)+(Math.hypot(P.vx,P.vy)/P.speed)*dt*(has('storm',2)?.36:.28);if(stormCharge>=1){stormCharge=0;let t=nearestEnemy();if(t){t.hp-=P.damage*(has('storm',3)?1.3:.8);chainFrom(t,P.damage*.4,has('storm',3)?3:0);if(t.hp<=0)killEnemy(t)}}}if(P.fortify){let m=Math.hypot(P.vx,P.vy);fortifyTime=m<20?fortifyTime+dt:Math.max(0,fortifyTime-dt*2)}if(P.overdrive){overdriveTime=Math.max(0,overdriveTime-dt)}}
let stormCharge=0,fortifyTime=0,overdriveTime=0;
function heal(v){P.hp=Math.min(P.maxHp,P.hp+v)}
function hurtPlayer(dmg,src){if(P.ifr>0)return;let fort=P.fortify&&fortifyTime>.7?.75:1;dmg=Math.max(1,dmg-P.armor*1.6)*fort;P.hp-=dmg;P.ifr=.38;if(P.thorns&&src&&src.hp){src.hp-=dmg*P.thorns;if(synergyActive('blood','thorn'))heal(dmg*P.thorns*P.lifesteal*.5)}for(let i=0;i<9;i++)particle(P.x,P.y,'#d85a52',rnd(140,30));if(P.hp<=0&&P.phoenix&&P.phoenixReady){P.phoenixReady=0;P.hp=has('phoenix',2)?35:1;P.ifr=has('phoenix',5)?6:2;explode(P.x,P.y,P.damage*4,170);toast('PHOENIX CLAUSE','DEATH REFUSED')}}
function dash(){if(paused||P.dashLeft>0)return;let x=joy.x,y=joy.y,m=Math.hypot(x,y);if(m<.1){x=P.vx||1;y=P.vy||0;m=Math.hypot(x,y)||1}x/=m;y/=m;P.x+=x*(has('swift',5)?170:135);P.y+=y*(has('swift',5)?170:135);P.ifr=.28;P.dashLeft=P.dashCd;if(has('thorn',5)){for(let i=0;i<4;i++)hazards.push({x:P.x-x*i*28,y:P.y-y*i*28,r:24,life:3,dmg:P.damage*.7,type:'thorn',enemy:false})}if(has('storm',4))stormCharge=Math.min(1,stormCharge+.4);for(let i=0;i<14;i++)particle(P.x,P.y,'#d9bc80',rnd(180,40))}
function particle(x,y,col,sp){let a=Math.random()*TAU;particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:rnd(.65,.2),col,size:rnd(3,1)})}
function hitFX(x,y,crit){for(let i=0;i<(crit?9:4);i++)particle(x,y,crit?'#f2cf76':'#dec8a4',rnd(120,30))}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;p.life-=dt}particles=particles.filter(p=>p.life>0)}

